# Simplified Math evaluation configuration
# This config avoids inheritance to reduce complexity and provide clearer error messages

defaults:
  - _self_
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

hydra:
  run:
    dir: ./outputs/math_eval/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./multirun/math_eval/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# Dataset Configuration - Load from HuggingFace GSM8K
dataset:
  _target_: eval_protocol.datasets.loader.load_and_process_dataset
  source_type: "huggingface"
  path_or_name: "openai/gsm8k"
  config_name: "main"  # Required for GSM8K dataset
  split: "test"  # Use test split for evaluation
  max_samples: 5  # Limit for quick testing
  column_mapping:
    user_query: "question"
    ground_truth_for_eval: "answer"
  hf_extra_load_params: {}

# System prompt for math problems (applied during generation)
system_prompt: "Solve the following math problem. Show your work clearly. Put the final numerical answer between <answer> and </answer> tags."

# Model Generation Configuration (enabled to generate responses to GSM8K questions)
generation:
  enabled: true
  _target_: eval_protocol.generation.generate_responses
  model_name: "accounts/fireworks/models/llama-v3p3-70b-reasoning"
  batch_size: 1
  max_new_tokens: 1024
  temperature: 0.0
  cache:
    enabled: true
  api_params:
    rate_limit_qps: 1.0
    max_retries: 3
    max_concurrent_requests: 5

# Reward Function Configuration
reward:
  function_path: "main.evaluate"
  params:
    tolerance: 0.001
    require_units: false

# Evaluation Parameters
evaluation_params:
  # To run on all samples, remove or comment out the line below
  limit_samples: 2

# Output Configuration
output:
  results_file: "eval_results.jsonl"
  preview_pairs_file: "preview_samples.jsonl"

logging_params:
  batch_log_interval: 10

# Other settings
seed: 42
verbose: true
