# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (^vite-app/|\.snap$)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: "(^vite-app/|\\.snap$)"
    -   id: end-of-file-fixer
        exclude: "(^vite-app/|\\.snap$)"
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: detect-private-key

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
    -   id: ruff-format
    -   id: ruff
        args: ["--fix"]
-   repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: 1.31.3
    hooks:
    -   id: basedpyright
        args: ["--level", "error"]
        env:
            NODE_OPTIONS: "--max-old-space-size=4096"
        # Only check Python files in the main package to reduce memory usage
        files: ^eval_protocol/.*\.py$
