# Simplified Braintrust evaluation configuration

defaults:
  - _self_
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

hydra:
  run:
    dir: ./outputs/braintrust_eval/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./multirun/braintrust_eval/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

# Dataset loading from HuggingFace GSM8K (reuse math example dataset)
dataset:
  _target_: eval_protocol.datasets.loader.load_and_process_dataset
  source_type: "huggingface"
  path_or_name: "openai/gsm8k"
  config_name: "main"
  split: "test"
  max_samples: 5
  column_mapping:
    user_query: question
    ground_truth_for_eval: answer
  hf_extra_load_params: {}

# Simple system prompt
system_prompt: "Solve the math problem and return the same text as the ground truth."

# Generation configuration using Fireworks
generation:
  enabled: true
  _target_: eval_protocol.generation.generate_responses
  model_name: "accounts/fireworks/models/qwen3-235b-a22b"
  batch_size: 1
  max_new_tokens: 50
  temperature: 0.0
  cache:
    enabled: true
  api_params:
    rate_limit_qps: 1.0
    max_retries: 3
    max_concurrent_requests: 5

# Reward function
reward:
  function_path: "main.evaluate"

# Evaluation parameters
evaluation_params:
  limit_samples: 2

# Output files
output:
  results_file: "eval_results.jsonl"
  preview_pairs_file: "preview_samples.jsonl"

logging_params:
  batch_log_interval: 10

seed: 42
verbose: true
