version: '3.8'

services:
  simulation-server:
    build:
      context: ../../../  # Build from project root
      dockerfile: examples/frozen_lake_mcp_complete/mcp_server/Dockerfile
    ports:
      - "8001:8000"  # Map host 8001 to container 8000
    environment:
      - PORT=8000
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
